In [1]:
import pandas as pd
import numpy as np
import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df =pd.read_csv('Cafe_sales.csv')

In [3]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023

In [ ]:
## Step two Inspecting the Structure of the data

In [4]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2,4,NaN,UNKNOWN,8/30/2023
9996,TXN_9659401,NaN,3,NaN,3,Digital Wallet,NaN,6/2/2023
9997,TXN_5255387,Coffee,4,2,8,Digital Wallet,NaN,3/2/2023
9998,TXN_7695629,Cookie,3,NaN,3,Digital Wallet,NaN,12/2/2023
9999,TXN_6170729,Sandwich,3,4,12,Cash,In-store,11/7/2023

In [15]:
df.shape

(10000, 8)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price_Per_Unit    9821 non-null   object
 4   Total_Spent       9827 non-null   object
 5   Payment_Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction_Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [10]:
df.rename(columns = {'Transaction ID': 'Transaction_ID','Price Per Unit' : 'Price_Per_Unit','Total Spent' : 'Total_Spent','Payment Method' : 'Payment_Method',
'Transaction Date' : 'Transaction_Date'}, inplace = True)

In [11]:
df.columns

Index(['Transaction_ID', 'Item', 'Quantity', 'Price_Per_Unit', 'Total_Spent',
       'Payment_Method', 'Location', 'Transaction_Date'],
      dtype='object')

In [5]:
list(df.columns)

['Transaction ID',
 'Item',
 'Quantity',
 'Price Per Unit',
 'Total Spent',
 'Payment Method',
 'Location',
 'Transaction Date']

In [17]:
df.dtypes

Transaction_ID      object
Item                object
Quantity            object
Price_Per_Unit      object
Total_Spent         object
Payment_Method      object
Location            object
Transaction_Date    object
dtype: object

In [18]:
df.describe()

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3,6,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [19]:
list(df.columns)

['Transaction_ID',
 'Item',
 'Quantity',
 'Price_Per_Unit',
 'Total_Spent',
 'Payment_Method',
 'Location',
 'Transaction_Date']

In [20]:
df.sample(5)

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
7112,TXN_7052672,Juice,1,3,3,ERROR,In-store,6/29/2023
5196,TXN_5083311,Sandwich,4,4,16,Digital Wallet,NaN,4/30/2023
2367,TXN_7852397,Tea,3,1.5,4.5,Cash,In-store,8/10/2023
6844,TXN_1759314,Salad,5,5,25,NaN,NaN,8/23/2023
1061,TXN_5442610,Juice,2,3,6,ERROR,Takeaway,12/10/2023

In [21]:
df.sample(10)

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
4152,TXN_9646000,ERROR,2,ERROR,UNKNOWN,NaN,In-store,12/14/2023
1704,TXN_9663990,Juice,1,3,3,NaN,NaN,1/6/2023
9818,TXN_6306555,Smoothie,1,4,4,Digital Wallet,Takeaway,4/12/2023
1514,TXN_8149585,Juice,1,3,3,Credit Card,ERROR,2/21/2023
3516,TXN_1152249,Smoothie,3,4,ERROR,NaN,In-store,5/9/2023
7983,TXN_7328209,Sandwich,3,4,12,Credit Card,NaN,3/1/2023
4356,TXN_6617283,Tea,4,1.5,6,Digital Wallet,NaN,6/9/2023
9276,TXN_7873479,Cookie,1,1,1,Credit Card,Takeaway,3/18/2023
9459,TXN_6966241,Juice,2,3,6,Digital Wallet,In-store,4/13/2023
8655,TXN_1931190,Cookie,3,1,3,UNKNOWN,Takeaway,12/31/2023

### Step 3: Initial Data Quality Assessment

In [4]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [5]:
df.nunique()

Transaction ID      10000
Item                   10
Quantity                7
Price Per Unit          8
Total Spent            19
Payment Method          5
Location                4
Transaction Date      367
dtype: int64

In [6]:
df["Payment Method"].value_counts(dropna=False)

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [7]:
df["Location"].value_counts(dropna=False)

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [8]:
df["Item"].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [9]:
df["Quantity"].value_counts(dropna=False)

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64

In [10]:
df["Price Per Unit"].value_counts(dropna=False)

Price Per Unit
3          2429
4          2331
2          1227
5          1204
1          1143
1.5        1133
ERROR       190
NaN         179
UNKNOWN     164
Name: count, dtype: int64

In [11]:
df["Total Spent"].value_counts(dropna=False)

Total Spent
6          979
12         939
3          930
4          923
20         746
15         734
8          677
10         524
2          497
9          479
5          468
16         444
25         259
7.5        237
1          232
4.5        225
1.5        205
NaN        173
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [12]:
df["Total Spent"].value_counts(dropna=False)

Total Spent
6          979
12         939
3          930
4          923
20         746
15         734
8          677
10         524
2          497
9          479
5          468
16         444
25         259
7.5        237
1          232
4.5        225
1.5        205
NaN        173
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

In [13]:
df["Transaction Date"].value_counts(dropna=False)

Transaction Date
UNKNOWN      159
NaN          159
ERROR        142
6/16/2023     40
2/6/2023      40
            ...
4/27/2023     15
9/24/2023     15
7/22/2023     14
3/11/2023     14
2/17/2023     14
Name: count, Length: 368, dtype: int64

### Step 4: Remove Unnecessary Columns.

At this stage, none of the columns should be removed.

Although Transaction ID may not be used for statistical analysis, it is valuable for:
Identifying duplicate records, Tracing individual transactions and Validating data integrity.

Therefore, I will keep all 8 columns.

### Step 5: Standardize Column Names.

In [6]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [7]:
df.columns

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date'],
      dtype='object')

### Step 6: Remove Spaces and Formatting Issues

In [8]:
df["item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [9]:
df["payment_method"].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [10]:
df["location"].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

### Step 7: Correct Data Types

In [12]:
df["quantity"] = df["quantity"].astype(int)

ValueError: invalid literal for int() with base 10: 'ERROR'

In [20]:
df['quantity'].sample(5)

3136        3
3316        3
5102    ERROR
612         5
8250        4
Name: quantity, dtype: object

In [13]:
df["quantity"] = df["quantity"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [14]:
df['quantity'].sample(5)

2639    2
5778    3
8816    2
2517    4
6074    3
Name: quantity, dtype: object

In [15]:
df["quantity"].value_counts(dropna=False)

quantity
5       2013
2       1974
4       1863
3       1849
1       1822
<NA>     341
NaN      138
Name: count, dtype: int64

In [16]:
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")

In [17]:
df["quantity"].dtype

dtype('float64')

In [18]:
df["quantity"].head(10)

0    2.0
1    4.0
2    4.0
3    2.0
4    2.0
5    5.0
6    3.0
7    4.0
8    5.0
9    5.0
Name: quantity, dtype: float64

In [19]:
df["price_per_unit"] = df["price_per_unit"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [20]:
df["price_per_unit"].value_counts(dropna=False)

price_per_unit
3       2429
4       2331
2       1227
5       1204
1       1143
1.5     1133
<NA>     354
NaN      179
Name: count, dtype: int64

In [21]:
df["price_per_unit"] = pd.to_numeric(df["price_per_unit"], errors="coerce")

In [22]:
df["price_per_unit"].dtype

dtype('float64')

In [23]:
df["total_spent"] = df["total_spent"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [24]:
df["total_spent"].value_counts(dropna=False)

total_spent
6       979
12      939
3       930
4       923
20      746
15      734
8       677
10      524
2       497
9       479
5       468
16      444
<NA>    329
25      259
7.5     237
1       232
4.5     225
1.5     205
NaN     173
Name: count, dtype: int64

In [25]:
df["total_spent"] = pd.to_numeric(df["total_spent"], errors="coerce")

In [26]:
df["total_spent"].dtype

dtype('float64')

In [27]:
df["transaction_date"] = df["transaction_date"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [28]:
df["transaction_date"].value_counts(dropna=False)

transaction_date
<NA>         301
NaN          159
2/6/2023      40
6/16/2023     40
7/21/2023     39
            ...
4/27/2023     15
9/24/2023     15
7/22/2023     14
3/11/2023     14
2/17/2023     14
Name: count, Length: 367, dtype: int64

In [29]:
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    errors="coerce"
)

In [30]:
df["transaction_date"].dtype

dtype('<M8[ns]')

### Step 8: Handle Missing Values

In [31]:
df.isna().sum()

transaction_id         0
item                 333
quantity             479
price_per_unit       533
total_spent          502
payment_method      2579
location            3265
transaction_date     460
dtype: int64

In [32]:
(df.isna().sum() / len(df)) * 100

transaction_id       0.00
item                 3.33
quantity             4.79
price_per_unit       5.33
total_spent          5.02
payment_method      25.79
location            32.65
transaction_date     4.60
dtype: float64

In [33]:
df["quantity"].describe()

count    9521.000000
mean        3.028463
std         1.419007
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: quantity, dtype: float64

In [42]:
df["price_per_unit"].describe()

count    9467.000000
mean        2.949984
std         1.278450
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: price_per_unit, dtype: float64

In [43]:
df["total_spent"].describe()

count    9498.000000
mean        8.924352
std         6.009919
min         1.000000
25%         4.000000
50%         8.000000
75%        12.000000
max        25.000000
Name: total_spent, dtype: float64

In [34]:
df[["quantity", "price_per_unit", "total_spent"]].isna().any(axis=1).sum()

np.int64(1456)

In [35]:
df[["quantity", "price_per_unit", "total_spent"]].isna().value_counts()

quantity  price_per_unit  total_spent
False     False           False          8544
          True            False           495
          False           True            462
True      False           False           441
False     True            True             20
True      False           True             20
          True            False            18
Name: count, dtype: int64

In [36]:
df.loc[
    df["total_spent"].isna() &
    df["quantity"].notna() &
    df["price_per_unit"].notna(),
    "total_spent"
] = (
    df["quantity"] * df["price_per_unit"]
)

In [37]:
df["total_spent"].isna().sum()

np.int64(40)

In [49]:
df.loc[
    df["price_per_unit"].isna() &
    df["quantity"].notna() &
    df["total_spent"].notna(),
    "price_per_unit"
] = (
    df["total_spent"] / df["quantity"]
)

In [38]:
df["price_per_unit"].isna().sum()

np.int64(533)

In [51]:
df.loc[
    df["quantity"].isna() &
    df["price_per_unit"].notna() &
    df["total_spent"].notna(),
    "quantity"
] = (
    df["total_spent"] / df["price_per_unit"]
)

In [39]:
df["quantity"].isna().sum()

np.int64(479)

In [40]:
df["quantity"].fillna(df["quantity"].median(), inplace=True)

In [41]:
df["quantity"].isna().sum()

np.int64(0)

In [42]:
df["price_per_unit"].fillna(df["price_per_unit"].median(), inplace=True)

In [43]:
df["price_per_unit"].isna().sum()

np.int64(0)

In [44]:
df["total_spent"].fillna(df["total_spent"].median(), inplace=True)

In [45]:
df["total_spent"].isna().sum()

np.int64(0)

In [46]:
df["item"] = df["item"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [47]:
df["item"].value_counts(dropna=False)

item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
<NA>         636
NaN          333
Name: count, dtype: int64

In [48]:
df["item"].isna().sum()

np.int64(969)

In [49]:
df["item"].fillna(df["item"].mode()[0], inplace=True)

In [50]:
df["item"].isna().sum()

np.int64(0)

In [51]:
df["payment_method"].value_counts(dropna=False)

payment_method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

In [52]:
df["payment_method"] = df["payment_method"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [53]:
df["payment_method"].isna().sum()

np.int64(3178)

In [54]:
df["payment_method"].fillna(df["payment_method"].mode()[0], inplace=True)

In [55]:
df["payment_method"].isna().sum()

np.int64(0)

In [56]:
df["location"].value_counts(dropna=False)

location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [57]:
df["location"] = df["location"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [58]:
df["location"].isna().sum()

np.int64(3961)

In [60]:
df["location"].fillna(df["location"].mode()[0], inplace=True)

In [61]:
df["location"].isna().sum()

np.int64(0)

In [62]:
df["transaction_date"].describe(datetime_is_numeric=True)

TypeError: NDFrame.describe() got an unexpected keyword argument 'datetime_is_numeric'

In [63]:
df["transaction_date"].describe()

count                             9540
mean     2023-07-01 23:00:31.698113280
min                2023-01-01 00:00:00
25%                2023-04-01 00:00:00
50%                2023-07-02 00:00:00
75%                2023-10-02 00:00:00
max                2023-12-31 00:00:00
Name: transaction_date, dtype: object

In [64]:
df["transaction_date"].fillna(df["transaction_date"].median(), inplace=True)

In [65]:
df.isna().sum()

transaction_id      0
item                0
quantity            0
price_per_unit      0
total_spent         0
payment_method      0
location            0
transaction_date    0
dtype: int64

### Step 9 : Check for Duplicate Records

In [66]:
df.duplicated().sum()

np.int64(0)

### Step 10 : Step: Check for Outliers

In [67]:
df["quantity"].describe()

count    10000.000000
mean         3.027100
std          1.384614
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: quantity, dtype: float64

In [68]:
df["price_per_unit"].describe()

count    10000.00000
mean         2.95265
std          1.24396
min          1.00000
25%          2.00000
50%          3.00000
75%          4.00000
max          5.00000
Name: price_per_unit, dtype: float64

In [69]:
df["total_spent"].describe()

count    10000.000000
mean         8.927200
std          5.992741
min          1.000000
25%          4.000000
50%          8.000000
75%         12.000000
max         25.000000
Name: total_spent, dtype: float64

In [71]:
df.to_csv("Cafe_Sales_Clean.csv", index=False)

            BY

 ## EBENEZER ADEBIYI